### ISSUE TITLE
Use of @openzeppelin/contracts-upgradeable/

### ISSUE THREAD

**Issue by RobertOttBS** [CMTA/CMTAT#109]
Hi,

First of all, concratulations for the nice work done within the CMTA project. It is great to see some 'standardization' on how to issue blockchain based company shares according to Swiss law.

I installed OpenZeppelin upgradable using:
$ npm install @openzeppelin/contracts-upgradeable

I then had to replace '../../openzeppelin-contracts-upgradeable/contracts/' with '@openzeppelin/contracts-upgradeable/' in all source files. Wouldn't it be better to directly refer to the  @openzeppelin/contracts-upgradeable in the import sections?

Kind Regards,

Robert

**Comment by rya-sge** [comment]
Hi Robert,

Thank you for your message and suggestion to improve the CMTAT,

The library OpenZeppelin is installed as a git submodule, see [USAGE.md#installation](https://github.com/CMTA/CMTAT/blob/master/doc/USAGE.md#installation).

The goal is also to be compatible with Foundry ( see [CMTAT-Foundry](https://github.com/CMTA/CMTAT-Foundry), which not use node modules at the moment.

Conclusion: unless there are specific advantages to use node modules instead of git submodule, we do not plan to change for node modules.

Kinds Regards,

Ryan

**Comment by RobertOttBS** [comment]
Thanks a lot for the explanations. Makes sence!
