### ISSUE TITLE
Gas optimisation

### ISSUE THREAD

**Issue by rya-sge** [CMTA/CMTAT#133]
- Make private the constants to store the different roles
- Use the external Visibility Modifier
https://exaud.com/how-to-reduce-gas-fee-on-blockchains/
https://www.alchemy.com/overviews/solidity-gas-optimization
https://deeprnd.medium.com/solidity-gas-optimisation-83c75170f534

**Comment by mariogutval** [comment]
Is this still relevant? We are planning to optimise the contract from gas perspective and we are focusing on the following issues:

Mandatory:

- Remove initializations to default values
- Uncheck index variable increment in for-loops
- Use calldata instead of memory wherever is possible
- Check require strings length

Optional:

- Substitute require statements with custom errors

Of course, everything is "mandatory" or optional" from our perspective.

**Comment by rya-sge** [comment]
Hello,

Thank you very much for your work !
Everything is good, except for "Remove initializations to default values"
It was a recommendation from the first audit, CVF-5, see [CMTAT-Audit-20210910-summary.pdf](https://github.com/CMTA/CMTAT/blob/master/doc/audits/CMTAT-Audit-20210910-summary.pdf)

```
Description This variable is not initialized.
Recommendation Consider explicitly initializing to 0 for readability.
```

**Comment by rya-sge** [comment]
Done
