### ISSUE TITLE
Add UUPS proxy support

### ISSUE THREAD

**Issue by diego-G** [CMTA/CMTAT#270]
> The original proxies included in OpenZeppelin followed the Transparent Proxy Pattern. While this pattern is still provided, our recommendation is now shifting towards UUPS proxies, which are both lightweight and versatile.

https://docs.openzeppelin.com/contracts/5.x/api/proxy

The downsides of Transparent vs UUPS are:
- It costs more gas to interact with since the proxy needs to determine whether to reroute the call and therefore needs to load the admin address on every call.
- It is more costly to deploy due to this extra logic.
- It requires an extra ProxyAdmin contract.

**Comment by rya-sge** [comment]
Hello Diego!
Thank you for your proposition, it makes sense !
Other advantage, in addition of the three you have mentioned:
- Same access control to upgrade the proxy than for other CMTAT functions (related to ProxyAdmin contract)
- Easy to implement since OpenZeppelin provides a library to use

Disadvantages:
- Add several additional internal functions and one external function which are not useful if you prefer using a beacon or a transparent proxy.  But the inheritance could be easily removed
- Increases CMTAT size code.


=> I am a little divided because the goal of the CMTAT is to offer flexibility and includes the UUPS architecture in CMTAT seems rather heavy to me. But it's definitely something to think about

**=> The simplest proposal would be to create a third deployment contract CMTAT_PROXY_UUPS which inherits of the OpenZeppelin library UUPS and implement the internal function _authorizeUpgrade.** Since it is at the end of the inheritance, it does not make any changes to the different modules and the internal CMTAT architecture.

If it's good for you, I'll go with that to implement UUPS

**Comment by rya-sge** [comment]
CMTAT UUPS version, first draft: [CMTAT_PROXY_UUPS.sol](https://github.com/CMTA/CMTAT/blob/manage-documents/contracts/CMTAT_PROXY_UUPS.sol)

**Comment by rya-sge** [comment]
Done
